### ISSUE TITLE
no human species

### ISSUE THREAD

**Issue by zhoudreames** [ablab/stringdecomposer#12]
There are no monomer information for my nohuman species,how can I identify the monomer sequence from my Assembly or reads sequence ? I have  X centromere assembly  sequence valiated by tandamtools ,and 50X hifi,100X ONT,100Pb etc reads pools .

**Comment by seryrzu** [comment]
Hi,

Sorry for very late response! Unfortunately, StringDecomposer does not support extraction of monomers de novo. However, we have done some progress for de novo extraction of monomers for all **human** centromeres. Please see ISMB 2021 [website](https://www.iscb.org/cms_addon/conferences/ismbeccb2021/proceedings.php#HitSeq:%20High-throughput%20Sequencing) — "CentromereArchitect: inference and analysis of the architecture of centromeres". The corresponding paper is in press. The tools need an initial guess of a monomer.
It is hard to predict how it will work on non-human genome, but we will very curious to take a look!

Best,
Andrey

**Comment by zhoudreames** [comment]
thanks for your reply~  again,how to I gain the consensus Alpha Satellite (AlphaSat.fa)?

**Comment by TanyaDvorkina** [comment]
Hi,

Consensus AlphaSat can be found in github of our new more general tool CentromereArchitect [https://github.com/ablab/centromere-architect/blob/dev/test_data/AlphaSat.fa](https://github.com/ablab/centromere-architect/blob/dev/test_data/AlphaSat.fa)

Also checkout our just published paper on Monomer Inference Algorithm in Bioinformatics: 
[CA paper](https://academic.oup.com/bioinformatics/article/37/Supplement_1/i196/6319687?login=true)

The latest version of the algorithm described there can be found here:
[https://github.com/ablab/centromere-architect/blob/dev/src/monomer_inference.py](https://github.com/ablab/centromere-architect/blob/dev/src/monomer_inference.py)

Do not hesitate to ask questions!

Best,
Tanya
